-- Users identified by email — no password, no verification. This is
-- intentionally an identifier, not authentication: the point is letting the
-- same person reach the same watchlist from a different device, not securing
-- the account. Real auth (verified email or OAuth) is a documented next step,
-- not something worth spending hackathon hours on when it doesn't touch the
-- actual differentiator (the mute mechanism).
CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  email TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Tickers tracked by the system (universe of stocks the synthetic generator drives)
CREATE TABLE IF NOT EXISTS tickers (
  symbol TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  base_price REAL NOT NULL,
  volatility REAL NOT NULL DEFAULT 0.02 -- used to normalize "meaningful" price move per stock
);

-- A user's watchlist
CREATE TABLE IF NOT EXISTS watchlist_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  symbol TEXT NOT NULL,
  added_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (symbol) REFERENCES tickers(symbol),
  UNIQUE(user_id, symbol)
);

-- Rolling price/volume history — synthetic generator writes here every tick
CREATE TABLE IF NOT EXISTS price_history (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  symbol TEXT NOT NULL,
  price REAL NOT NULL,
  volume INTEGER NOT NULL,
  recorded_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (symbol) REFERENCES tickers(symbol)
);

-- Alerts generated by the signal engine
CREATE TABLE IF NOT EXISTS alerts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  symbol TEXT NOT NULL,
  signal_type TEXT NOT NULL CHECK(signal_type IN ('price_move', 'volume_anomaly', 'range_breach')),
  status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending', 'approved', 'dismissed')),
  detail_json TEXT NOT NULL, -- raw numbers: price delta %, volume ratio, etc.
  explanation TEXT,          -- LLM-generated plain-language reasoning
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  resolved_at DATETIME,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (symbol) REFERENCES tickers(symbol)
);

-- Dismiss tracking that drives the mute mechanism
CREATE TABLE IF NOT EXISTS dismiss_counts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  symbol TEXT NOT NULL,
  signal_type TEXT NOT NULL CHECK(signal_type IN ('price_move', 'volume_anomaly', 'range_breach')),
  count INTEGER NOT NULL DEFAULT 0,
  muted_until DATETIME,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (symbol) REFERENCES tickers(symbol),
  UNIQUE(user_id, symbol, signal_type)
);

CREATE INDEX IF NOT EXISTS idx_price_history_symbol_time ON price_history(symbol, recorded_at);
CREATE INDEX IF NOT EXISTS idx_alerts_user_status ON alerts(user_id, status);
